name: Cloud Team CI Demo

on:
  push:
    branches: [ main, develop ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Print message
        run: echo "GitHub Actions working!"